import type { Metadata } from "next";
import "@/styles/globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";
import NoteProvider from "@/providers/NoteProvider";
import { KnownNoteIdsProvider } from "@/providers/KnownNoteIdsProvider";
import { WorkoutProfileEditorProvider } from "@/providers/WorkoutProfileEditorProvider";
import { AppSidebar } from "@/components/app-sidebar";
import { NavActions } from "@/components/nav-actions";
import { DateDisplay } from "@/components/DateDisplay";
import { getUser } from "@/auth/server";
import { getUserProfile } from "@/lib/user-utils";
import { Separator } from "@/components/ui/separator";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "Otium",
  description: "Generated by create next app",
};

// Force dynamic rendering since we use cookies for authentication
export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  const userProfile = await getUserProfile(user);

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NoteProvider>
            <KnownNoteIdsProvider>
              <SidebarProvider>
                <WorkoutProfileEditorProvider>
                  <AppSidebar user={user} userProfile={userProfile} />
                  <SidebarInset>
                    <header className="flex h-14 shrink-0 items-center justify-between">
                      <div className="flex items-center gap-2 px-3">
                        <SidebarTrigger />
                        <Separator
                          orientation="vertical"
                          className="mx-2 data-[orientation=vertical]:h-4"
                        />
                        <DateDisplay />
                      </div>
                      <div className="px-3">
                        <NavActions user={user} />
                      </div>
                    </header>
                    <div className="flex flex-1 flex-col gap-4 px-4 py-10">
                      {children}
                    </div>
                  </SidebarInset>
                </WorkoutProfileEditorProvider>
              </SidebarProvider>
            </KnownNoteIdsProvider>

            <Toaster />
          </NoteProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
